// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/data/models/chat_message_model.dart';
import 'app/data/models/chat_room_model.dart';
import 'app/data/models/user_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 12790774084620500),
    name: 'UserModel',
    lastPropertyId: const obx_int.IdUid(4, 8059238507281913918),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7540019943615903984),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8747007725309964270),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8557975432429717542),
        name: 'username',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 3948137124980824960),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8059238507281913918),
        name: 'password',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2267564712057135240),
    name: 'ChatMessageModel',
    lastPropertyId: const obx_int.IdUid(5, 7696219436314113396),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3444853466991228274),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6290576034609342455),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4123216944470245332),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3055819672919161152),
        name: 'chatRoomId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 5665937303908695428),
        relationField: 'chatRoom',
        relationTarget: 'ChatRoomModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7696219436314113396),
        name: 'senderId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 1967064503292770279),
        relationField: 'sender',
        relationTarget: 'UserModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6224291460023961899),
    name: 'ChatRoomModel',
    lastPropertyId: const obx_int.IdUid(2, 3979263424951001486),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8942107194665953246),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3979263424951001486),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'messages',
        srcEntity: 'ChatMessageModel',
        srcField: 'chatRoom',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 6224291460023961899),
    lastIndexId: const obx_int.IdUid(4, 3948137124980824960),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [6379517092237035335],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    UserModel: obx_int.EntityDefinition<UserModel>(
      model: _entities[0],
      toOneRelations: (UserModel object) => [],
      toManyRelations: (UserModel object) => {},
      getId: (UserModel object) => object.id,
      setId: (UserModel object, int id) {
        object.id = id;
      },
      objectToFB: (UserModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final usernameOffset = fbb.writeString(object.username);
        final passwordOffset = fbb.writeString(object.password);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, usernameOffset);
        fbb.addOffset(3, passwordOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final passwordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = UserModel(
          id: idParam,
          name: nameParam,
          username: usernameParam,
          password: passwordParam,
        );

        return object;
      },
    ),
    ChatMessageModel: obx_int.EntityDefinition<ChatMessageModel>(
      model: _entities[1],
      toOneRelations: (ChatMessageModel object) => [
        object.chatRoom,
        object.sender,
      ],
      toManyRelations: (ChatMessageModel object) => {},
      getId: (ChatMessageModel object) => object.id,
      setId: (ChatMessageModel object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageModel object, fb.Builder fbb) {
        final messageOffset = fbb.writeString(object.message);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, messageOffset);
        fbb.addInt64(2, object.timestamp);
        fbb.addInt64(3, object.chatRoom.targetId);
        fbb.addInt64(4, object.sender.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = ChatMessageModel(
          id: idParam,
          message: messageParam,
          timestamp: timestampParam,
        );
        object.chatRoom.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.chatRoom.attach(store);
        object.sender.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.sender.attach(store);
        return object;
      },
    ),
    ChatRoomModel: obx_int.EntityDefinition<ChatRoomModel>(
      model: _entities[2],
      toOneRelations: (ChatRoomModel object) => [],
      toManyRelations: (ChatRoomModel object) => {
        obx_int.RelInfo<ChatMessageModel>.toOneBacklink(
          4,
          object.id,
          (ChatMessageModel srcObject) => srcObject.chatRoom,
        ): object.messages,
      },
      getId: (ChatRoomModel object) => object.id,
      setId: (ChatRoomModel object, int id) {
        object.id = id;
      },
      objectToFB: (ChatRoomModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = ChatRoomModel(id: idParam, name: nameParam);
        obx_int.InternalToManyAccess.setRelInfo<ChatRoomModel>(
          object.messages,
          store,
          obx_int.RelInfo<ChatMessageModel>.toOneBacklink(
            4,
            object.id,
            (ChatMessageModel srcObject) => srcObject.chatRoom,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserModel] entity fields to define ObjectBox queries.
class UserModel_ {
  /// See [UserModel.id].
  static final id = obx.QueryIntegerProperty<UserModel>(
    _entities[0].properties[0],
  );

  /// See [UserModel.name].
  static final name = obx.QueryStringProperty<UserModel>(
    _entities[0].properties[1],
  );

  /// See [UserModel.username].
  static final username = obx.QueryStringProperty<UserModel>(
    _entities[0].properties[2],
  );

  /// See [UserModel.password].
  static final password = obx.QueryStringProperty<UserModel>(
    _entities[0].properties[3],
  );
}

/// [ChatMessageModel] entity fields to define ObjectBox queries.
class ChatMessageModel_ {
  /// See [ChatMessageModel.id].
  static final id = obx.QueryIntegerProperty<ChatMessageModel>(
    _entities[1].properties[0],
  );

  /// See [ChatMessageModel.message].
  static final message = obx.QueryStringProperty<ChatMessageModel>(
    _entities[1].properties[1],
  );

  /// See [ChatMessageModel.timestamp].
  static final timestamp = obx.QueryIntegerProperty<ChatMessageModel>(
    _entities[1].properties[2],
  );

  /// See [ChatMessageModel.chatRoom].
  static final chatRoom =
      obx.QueryRelationToOne<ChatMessageModel, ChatRoomModel>(
        _entities[1].properties[3],
      );

  /// See [ChatMessageModel.sender].
  static final sender = obx.QueryRelationToOne<ChatMessageModel, UserModel>(
    _entities[1].properties[4],
  );
}

/// [ChatRoomModel] entity fields to define ObjectBox queries.
class ChatRoomModel_ {
  /// See [ChatRoomModel.id].
  static final id = obx.QueryIntegerProperty<ChatRoomModel>(
    _entities[2].properties[0],
  );

  /// See [ChatRoomModel.name].
  static final name = obx.QueryStringProperty<ChatRoomModel>(
    _entities[2].properties[1],
  );

  /// see [ChatRoomModel.messages]
  static final messages =
      obx.QueryBacklinkToMany<ChatMessageModel, ChatRoomModel>(
        ChatMessageModel_.chatRoom,
      );
}
